#cloud-config
package_update: true
package_upgrade: true

users:
  - name: ubuntu
  - passwd: $6$rounds=4096$8KAJUp/v.fDw8$zP0lAxNXdXDEK/GtDr/2uWUs1TfY2lvmXR484pKkV4HeozBd6X5cLVPZlKa/uaOqzC5HS2kGutWAh87s1qk1r0

packages:
 - apt-transport-https
 - software-properties-common
 - gnome-keyring
 - python3-pip
 - python3-testresources
 - python3-keyrings.alt
 - wget
 - jq

runcmd:
  - sudo python3 -m pip install cxcli
  - sudo echo "auth     optional  pam_gnome_keyring.so" >> /etc/pam.d/login
  - sudo echo "session  optional  pam_gnome_keyring.so auto_start" >> /etc/pam.d/login
  - sudo echo "read -rsp \"[\`whoami\`] Unlock your keyring with your password. \" pass" >> /home/ubuntu/.profile
  - sudo echo "echo -n \"\$pass\" | gnome-keyring-daemon --login --daemonize" >> /home/ubuntu/.profile
  - sudo echo "echo \"\"" >> /home/ubuntu/.profile


  ### OPTIONAL
  ### Install abs-lang (https://www.abs-lang.org), and bring the joy back to shell scripting!
  ###
  # - wget https://github.com/abs-lang/abs/releases/latest/download/abs-linux-amd64 -O ./abs
  # - chmod +x ./abs
  # - ABSVER=`./abs --version`
  # - sudo mv ./abs /usr/local/bin/abs-${ABSVER}
  # - sudo ln -s /usr/local/bin/abs-${ABSVER} /usr/local/bin/abs

  ### OPTIONAL
  ### Install Powershell Core (https://docs.microsoft.com/en-us/powershell/scripting/overview),
  ### and bring the pain to your Linux CLI! :)
  ###
  # - wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
  # - sudo dpkg -i packages-microsoft-prod.deb
  # - sudo apt-get update
  # - sudo add-apt-repository universe
  # - sudo apt-get install -y powershell
  # - rm packages-microsoft-prod.deb

  - sudo reboot
